server:
  port: 8885

spring:
  application:
    name: gassman-telegram-bot-service
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

gassman:
  telegram:
    bot:
      username: YOUR_USERNAME
      token: YOUR_TOKEN
  list:
    cache:
      minutes: 0