server:
  port: 8886

spring:
  application:
    name: gassman-telegram-bot-service
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

gassman:
  telegram:
    bot:
      username: YOUR_USERNAME
      token: YOUR_TOKEN

  template:
    paymentInternalCreditURL: http://localhost:8881/gassman-payment-service/internal-credit/make/payment?%s