server:
  port: 8886

spring:
  application:
    name: gassman-telegram-bot-service
  rabbitmq:
    addresses: amqp://***
    cloud:
      stream:
        bindings:
          userRegistrationChannel:
            destination: gassman-user-registration
          userOrderChannel:
            destination: gassman-order-registration
          orderPaymentConfirmationChannel:
            destination: gassman-order-payment-confirmation
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000

gassman:
  telegram:
    bot:
      username: YOUR_USERNAME
      token: YOUR_TOKEN

  api:
    username:
    password: